kind: Service
apiVersion: v1
metadata:
  name: backend
spec:
  type: LoadBalancer
  selector:
    app: ucl-assistant
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ucl-assistant
      tier: backend
  template:
    metadata:
      labels:
        app: ucl-assistant
        tier: backend
        track: stable
    spec:
      containers:
        - name: backend
          image: "mbellgb/ucl-assistant-server:latest"
          ports:
            - name: http
              containerPort: 3000
          envFrom:
          - secretRef:
              name: ucl-assistant-backend-secret
          env:
          - name: PORT
            value: "3000"
          - name: REDIS_URL
            value: redis://redis-cluster:6379