version: '3.3' # compatible with docker engine -v 17.06
services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.13
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "nginx_conf:/etc/nginx/conf.d"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"
      - "certs:/etc/nginx/certs:ro"
  nginx-gen:
    container_name: nginx-gen
    build:
      context: ./
      dockerfile: Dockerfile.nginx-gen
    restart: always
    volumes:
      - "nginx_conf:/etc/nginx/conf.d"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "certs:/etc/nginx/certs:ro"
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    volumes:
      - "nginx_conf:/etc/nginx/conf.d"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - ACME_TOS_HASH=${ACME_TOS_HASH}

  redis_db:
    image: redis:4-alpine
    volumes:
    - redis:/data
  web:
    image: mbellgb/ucl-assistant-server
    container_name: web
    restart: always
    expose:
      - "3000"
    env_file:
      - ".env"
    environment:
      - REDIS_URL=redis://redis_db:6379
      - NODE_ENV=production
    depends_on:
      - redis
volumes:
  redis:
  nginx_conf:
  nginx_vhost:
  nginx_html:
  certs:

