groups:
  - name: app
    jobs:
      - job-app-test
      - full-test
resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/mbellgb/ucl-assistant
      branch: master
  - name: repo-app
    type: git
    source:
      uri: https://github.com/mbellgb/ucl-assistant
      branch: master
      paths: ["app/**/*"]
jobs:
  - name: job-app-test
    public: true
    plan:
      - get: repo-app
        trigger: true
      - task: test
        file: repo-app/ci/tasks/test.yml
        params:
          APP_NAME: app
        input_mapping: { repo: repo-app }
  - name: full-test
    public: true
    plan:
      - get: repo
        trigger: true
      - task: test
        file: repo/ci/tasks/test-all.yml
        input_mapping: { repo: repo }
